[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
base = "dark"
primaryColor = "#5463FF"
backgroundColor = "#111111"
secondaryBackgroundColor = "#31333F"
textColor = "#FAFAFA"
font = "sans serif"